data:
  image: busybox:latest
  volumes:
    - ./:/app
  entrypoint: tail -f /dev/null

app:
  build: docker/php
  working_dir: /app
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - db
    - memcached
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

nginx:
  image: nginx:latest
  ports:
    - "8003:8000"
  volumes:
    - ./:/app
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - app

memcached:
  restart: always
  image: memcached
  environment:
    MEMCACHED_MEMORY_LIMIT: 128

db:
  image: mongo:3.4
  ports:
    - "27018:27017"
  expose:
    - "27018"
  volumes:
    - ./data:/data:rw
  environment:
    MONGO_INITDB_ROOT_USERNAME: 'api_dbu'
    MONGO_INITDB_ROOT_PASSWORD: 'api_pass'